name: ai_cau
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^2.0.0
  flutter_chat_core: ^2.0.0
  flyer_chat_text_stream_message: ^2.0.0
  dio: ^5.9.0
  markdown: ^7.3.0
  gpt_markdown: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
